### ISSUE TITLE
Null Reference Exception when trying to import disk image

### ISSUE THREAD

**Issue by devscott** [xcp-ng/xcp#110]
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - Version: 7.6.1.16
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.42000
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 10.0.17134.0
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - Log Application State
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - ExitCode: 0
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - Time since process started: 00:01:06.8886947
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - Handles open: 1324
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - USER handles open: 442
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - GDI handles open: 169
2018-12-11 22:18:04,697 INFO  XenAdmin.Program [Main program thread] - Thread count: 47
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Virtual memory size: 39748177920 B(37 GB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Working set: 176619520 B(168 MB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Private memory size: 109871104 B(105 MB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Nonpaged system memory size: 94640 B(92 kB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Paged memory size: 109871104 B(105 MB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Paged system memory size: 1031104 B(1007 kB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Peak paged memory size: 115085312 B(110 MB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Peak virtual memory size: 39764881408 B(37 GB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Peak working set: 180789248 B(172 MB)
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Process priority class: Normal
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Privileged processor time: 00:00:05.3750000
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - Total processor time: 00:00:15.8593750
2018-12-11 22:18:04,712 INFO  XenAdmin.Program [Main program thread] - User processor time: 00:00:10.4843750
2018-12-11 22:20:03,553 INFO  XenOvf.OVF [Main program thread] - Import.Process: Found an Unknown Virtual Hardware Section (Rating: 5) [virtualbox-2.2]
2018-12-11 22:20:03,553 INFO  XenOvf.OVF [Main program thread] - Import.Process: Results may vary depending on hard disk image format.
2018-12-11 22:20:04,538 FATAL XenAdmin.Program [Main program thread] - Uncaught exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.Wizards.ImportWizard.OvfStorageResource.get_RequiredDiskCapacity()
   at XenAdmin.Wizards.GenericPages.SelectVMStorageWithMultipleVirtualDisksPage.PopulateSrComboBox(List`1 commonSRs)
   at XenAdmin.Wizards.GenericPages.SelectVMStorageWithMultipleVirtualDisksPage.PopulatePage()
   at XenAdmin.Controls.XenTabPage.PageLoaded(PageLoadedDirection direction)
   at XenAdmin.Wizards.XenWizardBase.WizardProgress_EnteringStep(Object sender, WizardProgressEventArgs e)
   at XenAdmin.Wizards.WizardProgress.OnEnteringStep(Boolean isForwardsTransition)
   at XenAdmin.Wizards.WizardProgress.NextStep()
   at XenAdmin.Wizards.XenWizardBase.buttonNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by olivierlambert** [comment]
Hi, this is an issue with XCP-ng Center, please open a ticket on XCP-ng Center repository :+1:
