### ISSUE TITLE
Installer: errors while importing GPG key (Failed to initialize NSS library) 

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#186]
```
INFO     [2019-05-09 15:48:55] TASK: Evaluating <function importYumAndRpmGpgKeys at 0x7f1820b328c0>[{'boot': '/tmp/root/boot', 'root': '/tmp/root', 'logs': '/tmp/root/var/log'}]
INFO     [2019-05-09 15:48:55] ran ['chroot', '/tmp/root', 'python', '/tmp/import_yum_keys.py']; rc 1
STANDARD ERROR:
error: Failed to initialize NSS library
Traceback (most recent call last):
  File "/tmp/import_yum_keys.py", line 3, in <module>
    from yum import YumBase
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 23, in <module>
    import rpm
  File "/usr/lib64/python2.7/site-packages/rpm/__init__.py", line 10, in <module>
    from rpm.transaction import *
  File "/usr/lib64/python2.7/site-packages/rpm/transaction.py", line 5, in <module>
    from rpm._rpm import ts as TransactionSetCore
ImportError: cannot import name ts

INFO     [2019-05-09 15:48:55] ran ['chroot', '/tmp/root', 'rpm', '--import', '/etc/pki/rpm-gpg/RPM-GPG-KEY-xcpng']; rc 1
STANDARD ERROR:
error: Failed to initialize NSS library
```

**Comment by olivierlambert** [comment]
Confirmed on my side, then update plugin is going mad in the logs :laughing:

**Comment by stormi** [comment]
Fixed. Newer `rpm` doesn't like that NSS fails to load, so you need to mount /dev into the chroot so that `/dev/urandom` is available.
