### ISSUE TITLE
error using xscontainer-prepare-vm

### ISSUE THREAD

**Issue by kifeo** [xcp-ng/xcp#198]
While following the procedure https://github.com/xcp-ng/xcp/wiki/Docker-in-XCP-ng, at the command 'scontainer-prepare-vm -v <VM_UUID> -u <username>' I got :+1: 

```
Traceback (most recent call last):
  File "/bin/xscontainer-prepare-vm", line 272, in <module>
    sys.exit(main())
  File "/bin/xscontainer-prepare-vm", line 246, in main
    resultcode = _handle_ssh(session, options)
  File "/bin/xscontainer-prepare-vm", line 139, in _handle_ssh
    resultcode = push_ssh_key(session, options.vmuuid, options.username)
  File "/bin/xscontainer-prepare-vm", line 80, in push_ssh_key
    print(docker.ERROR_CAUSE_NETWORK)
AttributeError: 'module' object has no attribute 'ERROR_CAUSE_NETWORK'
```

**Comment by stormi** [comment]
Hi, thanks for this report. From what I can see, it is an exception raised when trying to display an error message. So there was a real issue with your network configuration as seen from the xscontainer plugin, but it failed to display the error properly because it tried to print a non-existing attribute.

I'll report the bug about the failure to display the error message to the developers (Citrix developers), but I don't know what the root cause was exactly.

The function that failed first is this one: https://github.com/xenserver/xscontainer/blob/master/src/xscontainer/api_helper.py#L451. It seems that it's a function that is trying to get the VM IP. Were the xen guest tools installed in the VM? Had the VM an IP address?

**Comment by kifeo** [comment]
Hello,
Indeed I could test that with the xen guest tools it works, but generates the error if the tools are not installed.
I added a line  on the guide to correct this. (https://github.com/xcp-ng/xcp/wiki/Docker-in-XCP-ng)
Thanks !

**Comment by stormi** [comment]
Thanks for the feedback and the update of the wiki. I'll keep this issue open to track the upstream bug.

**Comment by LunarstarPony** [comment]
I'm getting this error even with Management agent 8.1 installed on Ubuntu 20.04.2 LTS tho Any idea why? VM Does have an IP Address
