### ISSUE TITLE
Importing VMs from xl toolstack

### ISSUE THREAD

**Issue by andrevalladares** [xcp-ng/xcp#262]
This might be a question more than an issue. Is there any guide out there to import VMs from another host that is currently running Xenserver 6.2 with the xl toolstack?

What I've tried so far is to create a new VM in xcp-ng center with the exact same configuration, and then copying the lvm partition (via dd) into the one created by the new VM process. The copy appears successful. This method of copying the lvm partition has worked for us has always worked between hosts with xl toolstacks

But when I tried starting the VM in xcp-ng center, I get the following error:

From the xcp-ng center log:

```
2019-08-27 16:03:11,349 WARN  XenAdmin.Network.TaskPoller [32] - Action failed due to API failure:
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at XenAdmin.Network.TaskPoller.poll()
   at XenAdmin.Network.TaskPoller.PollToCompletion()
   at XenAdmin.Actions.VMActions.VMStartAction.DoAction(Int32 start, Int32 end)
   at XenAdmin.Actions.VMActions.VMStartAbstractAction.StartOrResumeVmWithHa(Int32 start, Int32 end)
   at XenAdmin.Actions.VMActions.VMStartAction.Run()
   at XenAdmin.Actions.AsyncAction.RunWorkerThread(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-08-27 16:03:11,349 INFO  XenAPI.Session [32] - Invoking JSON-RPC method 'task.destroy'
2019-08-27 16:03:11,392 ERROR XenAdmin.Actions.AsyncAction [32] - An emulator required to run this VM failed to start
2019-08-27 16:03:11,392 ERROR XenAdmin.Actions.AsyncAction [32] -    at XenAdmin.Network.TaskPoller.poll()
   at XenAdmin.Network.TaskPoller.PollToCompletion()
   at XenAdmin.Actions.VMActions.VMStartAction.DoAction(Int32 start, Int32 end)
   at XenAdmin.Actions.VMActions.VMStartAbstractAction.StartOrResumeVmWithHa(Int32 start, Int32 end)
   at XenAdmin.Actions.VMActions.VMStartAction.Run()
   at XenAdmin.Actions.AsyncAction.RunWorkerThread(Object o)`
```
From xensource.log, the line I'm assuming is the relevant one:

```
Raised Server_error(FAILED_TO_START_EMULATOR, [ OpaqueRef:6a764a78-5078-4a38-babb-e8c974358269; domid 6; QMP failure at File "xc/device.ml", line 2364, characters 55-62 ])
```

I'm aware this isn't the usual route of doing this. If there's a better way of getting this VM in a xcp-ng 8 host, I'm all ears.

**Comment by olivierlambert** [comment]
Hi!

The forum might be a better place than a bug tracker to ask a question :wink: 

Anyway:
1. XenServer 6.2 got XAPI, not just xl. Are you sure it's XenServer 6.2?
2. If it's XS 6.2 you should be able to upgrade your old host
3. If it's XS 6.2 you should be able to even use copy feature of XO or even live migrate
4. Last question: is it a Windows XP VM?

**Comment by olivierlambert** [comment]
You can follow this guide I wrote a while ago: https://xen-orchestra.com/blog/migrate-from-xen-to-xenserver/

Good luck and feel free to post on XCP-ng forum if you need further assistance :+1:
