### ISSUE TITLE
Templates for RHEL 8 and CentOS 8 on XCP-ng

### ISSUE THREAD

**Issue by agador** [xcp-ng/xcp#274]
Are there going to be templates for REHL 8.0 and CentOS 8.0 VM installs?  I realize CentOS 8.0 isn't going to be released for a couple more days, but REHL 8.0 has been out for a while now. 

Are they necessary to creating VMs with REHL 8.0 or CentOS 8.0 media?

Jim

**Comment by olivierlambert** [comment]
It's not vital. You can use a RHEL 7 template, it will work fine. However, we'll see to add those templates.

**Comment by agador** [comment]
Thanks Oliver!

**Comment by stormi** [comment]
I have added templates for RHEL 8 and derivatives, as well as a template for Debian 10.

You can test them by installing the update candidate:
```
yum update guest-templates* --enablerepo=xcp-ng-testing
```

**Comment by stormi** [comment]
Note: there's also an update candidate for guest tools for RHEL 8 and derivatives:
```
# first make sure to eject the tools ISO image from existing VMs

# then:
yum update xcp-ng-pv-tools --enablerepo=xcp-ng-testing
```

**Comment by stormi** [comment]
Question on the forum "installed and tried to use a centos8 template. It does not allow to use UEFI. Is this intended?". 

Yes, because UEFI support is still experimental, and the template is meant for the larger use cases. Is that important to you?

**Comment by agador** [comment]
The new tools disk will not mount in XOA:

error log:

vm.insertCd
{
  "id": "567f214a-8836-6b4e-5866-a7e5041758c5",
  "cd_id": "b8af8106-93af-4fca-acc8-4e94aa392020",
  "force": true
}
{
  "code": "VDI_MISSING",
  "params": [
    "OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d",
    "OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26"
  ],
  "task": {
    "uuid": "0f01905c-e08b-f246-3097-f5ef9a81a44c",
    "name_label": "Async.VBD.insert",
    "name_description": "",
    "allowed_operations": [],
    "current_operations": {},
    "created": "20191016T11:06:56Z",
    "finished": "20191016T11:06:56Z",
    "status": "failure",
    "resident_on": "OpaqueRef:a63b77c5-780a-48f3-b870-9cd223d4e491",
    "progress": 1,
    "type": "<none/>",
    "result": "",
    "error_info": [
      "VDI_MISSING",
      "OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d",
      "OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26"
    ],
    "other_config": {},
    "subtask_of": "OpaqueRef:NULL",
    "subtasks": [],
    "backtrace": "(((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi-client/client.ml)(line 6))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi-client/client.ml)(line 18))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi-client/client.ml)(line 12431))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 24))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 35))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi/message_forwarding.ml)(line 103))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 24))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi/rbac.ml)(line 236))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi/server_helpers.ml)(line 83)))"
  },
  "message": "VDI_MISSING(OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d, OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26)",
  "name": "XapiError",
  "stack": "XapiError: VDI_MISSING(OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d, OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26)
    at Function.wrap (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_XapiError.js:16:11)
    at _default (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_getTaskResult.js:11:28)
    at Xapi._addRecordToCache (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:812:37)
    at events.forEach.event (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:833:13)
    at Array.forEach (<anonymous>)
    at Xapi._processEvents (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:823:11)
    at /usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:984:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/dist/index.js:60:103)
    at _next (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/dist/index.js:62:194)
    at tryCatcher (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)"
}

**Comment by agador** [comment]
Also, the new REHL/CentOS 8 templates are not showing in XOA.

**Comment by agador** [comment]
Oops.. missed a step with the templates.

**Comment by agador** [comment]
Stil getting error on attaching the tools-disk

vm.insertCd
{
  "id": "d751dc1c-c0ed-ecac-edea-6c8e7504e5c1",
  "cd_id": "b8af8106-93af-4fca-acc8-4e94aa392020",
  "force": true
}
{
  "code": "VDI_MISSING",
  "params": [
    "OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d",
    "OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26"
  ],
  "task": {
    "uuid": "b824bd59-fc26-5508-460a-06a4bbe85760",
    "name_label": "Async.VBD.insert",
    "name_description": "",
    "allowed_operations": [],
    "current_operations": {},
    "created": "20191016T11:32:39Z",
    "finished": "20191016T11:32:39Z",
    "status": "failure",
    "resident_on": "OpaqueRef:a63b77c5-780a-48f3-b870-9cd223d4e491",
    "progress": 1,
    "type": "<none/>",
    "result": "",
    "error_info": [
      "VDI_MISSING",
      "OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d",
      "OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26"
    ],
    "other_config": {},
    "subtask_of": "OpaqueRef:NULL",
    "subtasks": [],
    "backtrace": "(((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi-client/client.ml)(line 6))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi-client/client.ml)(line 18))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi-client/client.ml)(line 12431))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 24))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 35))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi/message_forwarding.ml)(line 103))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 24))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi/rbac.ml)(line 236))((process\"xapi @ xcpng-800-fx2-2-1a\")(filename ocaml/xapi/server_helpers.ml)(line 83)))"
  },
  "message": "VDI_MISSING(OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d, OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26)",
  "name": "XapiError",
  "stack": "XapiError: VDI_MISSING(OpaqueRef:8b121926-4a43-4b2c-bb16-d95d607dcb1d, OpaqueRef:3fb656bf-a9c5-430a-936b-ac850256aa26)
    at Function.wrap (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_XapiError.js:16:11)
    at _default (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_getTaskResult.js:11:28)
    at Xapi._addRecordToCache (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:812:37)
    at events.forEach.event (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:833:13)
    at Array.forEach (<anonymous>)
    at Xapi._processEvents (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:823:11)
    at /usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:984:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/dist/index.js:60:103)
    at _next (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/dist/index.js:62:194)
    at tryCatcher (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/xo-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)"
}

Also, the of note.. the new tools disk is lightly greyed out in XOA

![Screen Shot 2019-10-16 at 4 34 12 AM](https://user-images.githubusercontent.com/5614581/66915638-58956d00-efce-11e9-9285-3f1544c0ebc4.png)

**Comment by agador** [comment]
Ok.. so after a pool-reboot, the tools-cd now shows up and attaches correctly.  First I tried a xe-toolstack-restart... that did NOT work.

It took a complete pool boot to get the CD to show up correctly and attach as expected.

Other than that... both the templates and the tools-cd work just fine for CentOS 8.

Thanks!

**Comment by cnaumer** [comment]
installed and tried to use a centos8 template. It does not allow to use UEFI. Is this intended?

**Comment by stormi** [comment]
Quoting what I answered above to this question:

> Yes, because UEFI support is still experimental, and the template is meant for the larger use cases. You can still use the "Other installation media" template, it will work the same. Is that important to you?

**Comment by cnaumer** [comment]
No this was just an observation. I have no Problem with that.
Tried the template now for a centos8 install and everything worked so far.

**Comment by nagilum99** [comment]
Question for yourself: What sense does it make, to write down this observation, as it was already mentioned (and your question answered) here?

**Comment by cnaumer** [comment]
None at all. Note to self -> read all comments before posting

**Comment by olivierlambert** [comment]
:laughing: it happens to everyone sometimes :wink:

**Comment by stormi** [comment]
Update published
