### ISSUE TITLE
Force Shutdown failed

### ISSUE THREAD

**Issue by Linh1706** [xcp-ng/xcp#344]
Got error while playing with VM. cannot shutdown Vm
This is the error message from XCP Center:

"Failed","Shutting down VM 'Ubuntu 18.04' on 'xcp-ng-ryzen'","xcp-ng-ryzen","Mar 8, 2020 1:11 AM"

And this is log from XO:

vm.stop
{
  "id": "f4bb0a87-88af-a8cf-6757-a255d67448b2",
  "force": true
}
{
  "code": "INTERNAL_ERROR",
  "params": [
    "VM not in expected power state after completing operation",
    "OpaqueRef:6c0b8041-e1d0-4fc7-980b-74f3bb86dae4",
    "halted",
    "running"
  ],
  "task": {
    "uuid": "43ad647c-b54b-aad1-0226-4a86ee96f077",
    "name_label": "Async.VM.hard_shutdown",
    "name_description": "",
    "allowed_operations": [],
    "current_operations": {},
    "created": "20200307T18:11:58Z",
    "finished": "20200307T18:11:58Z",
    "status": "failure",
    "resident_on": "OpaqueRef:79ec8c30-f1cb-4a23-94e5-3c2b3af795da",
    "progress": 1,
    "type": "<none/>",
    "result": "",
    "error_info": [
      "INTERNAL_ERROR",
      "VM not in expected power state after completing operation",
      "OpaqueRef:6c0b8041-e1d0-4fc7-980b-74f3bb86dae4",
      "halted",
      "running"
    ],
    "other_config": {
      "debug_info:cancel_points_seen": "6"
    },
    "subtask_of": "OpaqueRef:NULL",
    "subtasks": [],
    "backtrace": "(((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/xapi_vm_lifecycle.ml)(line 702))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/xapi_xenops.ml)(line 2873))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/xapi_xenops.ml)(line 2503))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/xapi_xenops.ml)(line 2577))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/xapi_vm.ml)(line 339))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/message_forwarding.ml)(line 100))((process\"xapi @ xcp-ng-ryzen\")(filename lib/xapi-stdext-pervasives/pervasiveext.ml)(line 24))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/rbac.ml)(line 236))((process\"xapi @ xcp-ng-ryzen\")(filename ocaml/xapi/server_helpers.ml)(line 83)))"
  },
  "message": "INTERNAL_ERROR(VM not in expected power state after completing operation, OpaqueRef:6c0b8041-e1d0-4fc7-980b-74f3bb86dae4, halted, running)",
  "name": "XapiError",
  "stack": "XapiError: INTERNAL_ERROR(VM not in expected power state after completing operation, OpaqueRef:6c0b8041-e1d0-4fc7-980b-74f3bb86dae4, halted, running)
    at Function.wrap (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/src/_XapiError.js:16:12)
    at _default (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/src/_getTaskResult.js:11:29)
    at Xapi._addRecordToCache (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/src/index.js:828:24)
    at forEach (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/src/index.js:849:14)
    at Array.forEach (<anonymous>)
    at Xapi._processEvents (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/src/index.js:839:12)
    at /etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/src/index.js:1000:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/dist/index.js:62:103)
    at _next (/etc/xo/xo-builds/xen-orchestra-202001030755/packages/xen-api/dist/index.js:64:194)
    at tryCatcher (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/etc/xo/xo-builds/xen-orchestra-202001030755/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)"
}

**Comment by olivierlambert** [comment]
Hi,

This Github repo is more for reproducible/confirmed bugs, please report on https://xcp-ng.org/forum first :) 

Thanks!
