### ISSUE TITLE
Shared storage & XCP-ng tools show partially connected when 1 of 2 hosts shutdown. 

### ISSUE THREAD

**Issue by brezlord** [xcp-ng/xcp#439]
Both hosts on 8.2.0-beta, shut down host-02 which was not the pool master and the shared storage & XCP-ng tools show partially connected and no stats available for storage. Reboot host-02 and shared storage & XCP-ng tools is now healthy and stats are back. Disabled host-02 and shutdown and still had the same issue as above. The only way to get the stats, the shared storage & XCP-ng tools back to healthy status is to forget the storage attached to host-02 that was shut down or remove the host from the pool.

xo-server 5.67.0 xo-web 5.71.0

I get the following error in XO logs when selecting the SR in XO and clicking on stats. HOME-->STORGES-->NFS SSD SR-->STATS
```
host.stats
{
  "host": "2906456d-cfaf-46e9-90a0-eb7e616ab104"
}
{
  "code": "HOST_OFFLINE",
  "params": [
    "OpaqueRef:ca7da371-07fc-4b95-b7a7-34ed1febbf26"
  ],
  "call": {
    "method": "host.get_servertime",
    "params": [
      "OpaqueRef:ca7da371-07fc-4b95-b7a7-34ed1febbf26"
    ]
  },
  "message": "HOST_OFFLINE(OpaqueRef:ca7da371-07fc-4b95-b7a7-34ed1febbf26)",
  "name": "XapiError",
  "stack": "XapiError: HOST_OFFLINE(OpaqueRef:ca7da371-07fc-4b95-b7a7-34ed1febbf26)
    at Function.wrap (/opt/xen-orchestra/packages/xen-api/src/_XapiError.js:16:12)
    at /opt/xen-orchestra/packages/xen-api/src/transports/json-rpc.js:35:27
    at tryCatcher (/opt/xen-orchestra/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/xen-orchestra/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/xen-orchestra/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/xen-orchestra/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/xen-orchestra/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/opt/xen-orchestra/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/xen-orchestra/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/xen-orchestra/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/xen-orchestra/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)"
}
```

**Comment by olivierlambert** [comment]
Hi,

It's not clear what's the problem and what do you expect?

**Comment by brezlord** [comment]
I would of thought that if a host is shut down that the shared storage & XCP-ng tools would stay healthy and green and that the stats for the NFS SR would still work. Not all hosts would be on all the time. eg you might have a pool with 4 hosts but only 3 running and one is powered off as a spare.

**Comment by olivierlambert** [comment]
XCP-ng is "meant" to have all hosts up, otherwise, indeed, one SR isn't really healthy in the way it's not connected to all hosts. I don't think it's a common use-case to do that. But regarding the green dots, it's more an XO question than XCP-ng (a "cosmetic" issue, meaning you consider it's normal to have a SR unplugged on a halted host).

**Comment by brezlord** [comment]
What about the stats not working? I'm new to Xen. For eg at work running several dell blade centers on ESXi not all blades are powered on. Some are off and only powered on for maintenance to occur on online blade , failure of online blade or more compute needed.

**Comment by stormi** [comment]
Indeed, the stats not working because of a shutdown host is the reason why I asked for an issue to be created. Especially in the case when the host is explicitly disabled before shutdown.

**Comment by brezlord** [comment]
If a host is shutdown it is to be expected that that host is not connected to the shared storage and therefore XO should not indicate that there is a problem with the shared storage.

**Comment by brezlord** [comment]
Another strange thing with the stats, when all hosts are online write latincy ~4mSec shut down one host and it goes up to ~8mSec with no change in VM load.
