### ISSUE TITLE
xcp-ng 8.2 fresh install does not boot and in safe-mode template list is limited

### ISSUE THREAD

**Issue by rhtyd** [xcp-ng/xcp#479]
I'm trying to install xcp-ng in a VM (on KVM/qemu, on amd threadripper 1950x machine) for CI/testing, for adding support in CloudStack https://github.com/apache/cloudstack/pull/4672

However, the boot does not work out of the box. I've to use safe mode to get the installer up and after installation as well, I figured one way to fix the boot issue was to add `no-bootscrub max_cstate=0 ` in the grub.cfg. However, on setup the `xe template-list` returns limited no. of templates.

To manually fix it I run the create-template script that fails:
```
/usr/bin/create-guest-templates
Load /usr/share/xapi/vm-templates/windows-server-2012-64bit.json
Load /usr/share/xapi/vm-templates/centos-7.json
Load /usr/share/xapi/vm-templates/sled-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/rhel-8.json
Load /usr/share/xapi/vm-templates/rhel-7.json
Load /usr/share/xapi/vm-templates/sle-15-64bit.json
Load /usr/share/xapi/vm-templates/debian-9.json
Load /usr/share/xapi/vm-templates/windows-8-64bit.json
Load /usr/share/xapi/vm-templates/base-windows.json
Load /usr/share/xapi/vm-templates/base-sle-hvm.json
Load /usr/share/xapi/vm-templates/windows-10-64bit.json
Load /usr/share/xapi/vm-templates/oel-7.json
Load /usr/share/xapi/vm-templates/coreos.json
Load /usr/share/xapi/vm-templates/windows-server-2012-r2-64bit.json
Load /usr/share/xapi/vm-templates/sles-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/windows-server-2016-64bit.json
Load /usr/share/xapi/vm-templates/oel-8.json
Load /usr/share/xapi/vm-templates/base-sle-hvm-64bit.json
Load /usr/share/xapi/vm-templates/base-kylin-7.json
Load /usr/share/xapi/vm-templates/kylin-7.json
Load /usr/share/xapi/vm-templates/debian-8.json
Load /usr/share/xapi/vm-templates/windows-server-2019-64bit.json
Load /usr/share/xapi/vm-templates/sled-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-uefi.json
Load /usr/share/xapi/vm-templates/sles-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/sl-7.json
Load /usr/share/xapi/vm-templates/ubuntu-20.04.json
Load /usr/share/xapi/vm-templates/windows-10-32bit.json
Load /usr/share/xapi/vm-templates/ubuntu-16.04.json
Load /usr/share/xapi/vm-templates/other-install-media.json
Load /usr/share/xapi/vm-templates/windows-8-32bit.json
Load /usr/share/xapi/vm-templates/base-hvmlinux.json
Load /usr/share/xapi/vm-templates/base-el-7.json
Load /usr/share/xapi/vm-templates/centos-8.json
Load /usr/share/xapi/vm-templates/sles-12-sp5-64bit.json
Load /usr/share/xapi/vm-templates/debian-10.json
Load /usr/share/xapi/vm-templates/ubuntu-18.04.json
Load /usr/share/xapi/vm-templates/base-windows-8.json
Destroy 4b6425be-728a-4a2c-8333-0aef209a348b
Insert 4b6425be-728a-4a2c-8333-0aef209a348b
Traceback (most recent call last):
  File "/usr/bin/create-guest-templates", line 17, in <module>
    loader.insert_templates()
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 187, in insert_templates
    self._insert_template(i)
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 159, in _insert_template
    conn.request("PUT", "/import_metadata?" + params, tar)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 885, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 857, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
```

I checked xapi is running:
```
# systemctl status xapi
● xapi.service - XenAPI server (XAPI)
   Loaded: loaded (/usr/lib/systemd/system/xapi.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/xapi.service.d
           └─local.conf, slice.conf
   Active: active (running) since Fri 2021-02-19 16:39:29 UTC; 12min ago
  Process: 2062 ExecStartPost=/usr/bin/touch /var/lock/subsys/xapi (code=exited, status=0/SUCCESS)
 Main PID: 2061 (xapi)
   CGroup: /control.slice/xapi.service
           └─2061 /opt/xensource/bin/xapi -nowatchdog -writereadyfile /var/run/xapi_startup.cookie -writeinitcomplete /var/run/xapi_init_complete.cookie -onsystemboot
```
cc @olivierlambert @shwstppr

**Comment by olivierlambert** [comment]
Thanks for your feedback!

This issue is happening every time?

**Comment by rhtyd** [comment]
Yes on fresh install using this ISO - https://mirrors.xcp-ng.org/isos/8.2/xcp-ng-8.2.0.iso?https=1
I'm now trying to do a yum update and restart with latest to see if it fixes itself @olivierlambert 

I've built the qcow2 template here where the issue is seen (not all templates available) - https://download.cloudstack.org/templates/mbx/xcpng82.qcow2

**Comment by rhtyd** [comment]
I did one more, this time restarting xe-toolstack:
```
[16:58 localhost ~]# create-guest-templates
Load /usr/share/xapi/vm-templates/windows-server-2012-64bit.json
Load /usr/share/xapi/vm-templates/centos-7.json
Load /usr/share/xapi/vm-templates/sled-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/rhel-8.json
Load /usr/share/xapi/vm-templates/rhel-7.json
Load /usr/share/xapi/vm-templates/sle-15-64bit.json
Load /usr/share/xapi/vm-templates/debian-9.json
Load /usr/share/xapi/vm-templates/windows-8-64bit.json
Load /usr/share/xapi/vm-templates/base-windows.json
Load /usr/share/xapi/vm-templates/base-sle-hvm.json
Load /usr/share/xapi/vm-templates/windows-10-64bit.json
Load /usr/share/xapi/vm-templates/oel-7.json
Load /usr/share/xapi/vm-templates/coreos.json
Load /usr/share/xapi/vm-templates/windows-server-2012-r2-64bit.json
Load /usr/share/xapi/vm-templates/sles-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/windows-server-2016-64bit.json
Load /usr/share/xapi/vm-templates/oel-8.json
Load /usr/share/xapi/vm-templates/base-sle-hvm-64bit.json
Load /usr/share/xapi/vm-templates/base-kylin-7.json
Load /usr/share/xapi/vm-templates/kylin-7.json
Load /usr/share/xapi/vm-templates/debian-8.json
Load /usr/share/xapi/vm-templates/windows-server-2019-64bit.json
Load /usr/share/xapi/vm-templates/sled-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-uefi.json
Load /usr/share/xapi/vm-templates/sles-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/sl-7.json
Load /usr/share/xapi/vm-templates/ubuntu-20.04.json
Load /usr/share/xapi/vm-templates/windows-10-32bit.json
Load /usr/share/xapi/vm-templates/ubuntu-16.04.json
Load /usr/share/xapi/vm-templates/other-install-media.json
Load /usr/share/xapi/vm-templates/windows-8-32bit.json
Load /usr/share/xapi/vm-templates/base-hvmlinux.json
Load /usr/share/xapi/vm-templates/base-el-7.json
Load /usr/share/xapi/vm-templates/centos-8.json
Load /usr/share/xapi/vm-templates/sles-12-sp5-64bit.json
Load /usr/share/xapi/vm-templates/debian-10.json
Load /usr/share/xapi/vm-templates/ubuntu-18.04.json
Load /usr/share/xapi/vm-templates/base-windows-8.json
Destroy 552bce37-51b2-445d-84f2-5f33fa112d7e
Insert 552bce37-51b2-445d-84f2-5f33fa112d7e
Insert 4383f051-cc9e-48d5-99e9-8fa2e979e2d0
Traceback (most recent call last):
  File "/usr/bin/create-guest-templates", line 17, in <module>
    loader.insert_templates()
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 187, in insert_templates
    self._insert_template(i)
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 159, in _insert_template
    conn.request("PUT", "/import_metadata?" + params, tar)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 885, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 857, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
[16:58 localhost ~]# xe-toolstack-restart 
Executing xe-toolstack-restart
done.
[16:58 localhost ~]# create-guest-templates
Load /usr/share/xapi/vm-templates/windows-server-2012-64bit.json
Load /usr/share/xapi/vm-templates/centos-7.json
Load /usr/share/xapi/vm-templates/sled-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/rhel-8.json
Load /usr/share/xapi/vm-templates/rhel-7.json
Load /usr/share/xapi/vm-templates/sle-15-64bit.json
Load /usr/share/xapi/vm-templates/debian-9.json
Load /usr/share/xapi/vm-templates/windows-8-64bit.json
Load /usr/share/xapi/vm-templates/base-windows.json
Load /usr/share/xapi/vm-templates/base-sle-hvm.json
Load /usr/share/xapi/vm-templates/windows-10-64bit.json
Load /usr/share/xapi/vm-templates/oel-7.json
Load /usr/share/xapi/vm-templates/coreos.json
Load /usr/share/xapi/vm-templates/windows-server-2012-r2-64bit.json
Load /usr/share/xapi/vm-templates/sles-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/windows-server-2016-64bit.json
Load /usr/share/xapi/vm-templates/oel-8.json
Load /usr/share/xapi/vm-templates/base-sle-hvm-64bit.json
Load /usr/share/xapi/vm-templates/base-kylin-7.json
Load /usr/share/xapi/vm-templates/kylin-7.json
Load /usr/share/xapi/vm-templates/debian-8.json
Load /usr/share/xapi/vm-templates/windows-server-2019-64bit.json
Load /usr/share/xapi/vm-templates/sled-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-uefi.json
Load /usr/share/xapi/vm-templates/sles-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/sl-7.json
Load /usr/share/xapi/vm-templates/ubuntu-20.04.json
Load /usr/share/xapi/vm-templates/windows-10-32bit.json
Load /usr/share/xapi/vm-templates/ubuntu-16.04.json
Load /usr/share/xapi/vm-templates/other-install-media.json
Load /usr/share/xapi/vm-templates/windows-8-32bit.json
Load /usr/share/xapi/vm-templates/base-hvmlinux.json
Load /usr/share/xapi/vm-templates/base-el-7.json
Load /usr/share/xapi/vm-templates/centos-8.json
Load /usr/share/xapi/vm-templates/sles-12-sp5-64bit.json
Load /usr/share/xapi/vm-templates/debian-10.json
Load /usr/share/xapi/vm-templates/ubuntu-18.04.json
Load /usr/share/xapi/vm-templates/base-windows-8.json
Destroy 552bce37-51b2-445d-84f2-5f33fa112d7e
Insert 552bce37-51b2-445d-84f2-5f33fa112d7e
Insert 2cf37285-57bc-4633-a24f-0c6c825dda66
Traceback (most recent call last):
  File "/usr/bin/create-guest-templates", line 17, in <module>
    loader.insert_templates()
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 187, in insert_templates
    self._insert_template(i)
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 159, in _insert_template
    conn.request("PUT", "/import_metadata?" + params, tar)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 885, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 857, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe

```

**Comment by olivierlambert** [comment]
I have the feeling there's an issue with the KVM/qemu, affecting the dom0.

Do you have the same problem with 8.1?

**Comment by rhtyd** [comment]
The VM has been given 6GB RAM and 4 cores with host-passthrough settting. I'll try 8.1 @olivierlambert on the same machine and keep you posted. Thanks for replying so quickly :)

**Comment by rhtyd** [comment]
@olivierlambert weird it works now. I did the following:
- yum update to update all pkgs
- reboot into new kernel - it fails, so tried again with max_cstate=0 option (this is to ensure cpu cores don't sleep per the kernel docs)
-  next I ran the commands and they worked:

```
# xe-toolstack-restart 
Executing xe-toolstack-restart
done.
[17:03 localhost ~]# create-guest-templates
Load /usr/share/xapi/vm-templates/windows-server-2012-64bit.json
Load /usr/share/xapi/vm-templates/centos-7.json
Load /usr/share/xapi/vm-templates/sled-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/rhel-8.json
Load /usr/share/xapi/vm-templates/rhel-7.json
Load /usr/share/xapi/vm-templates/sle-15-64bit.json
Load /usr/share/xapi/vm-templates/debian-9.json
Load /usr/share/xapi/vm-templates/windows-8-64bit.json
Load /usr/share/xapi/vm-templates/base-windows.json
Load /usr/share/xapi/vm-templates/base-sle-hvm.json
Load /usr/share/xapi/vm-templates/windows-10-64bit.json
Load /usr/share/xapi/vm-templates/oel-7.json
Load /usr/share/xapi/vm-templates/coreos.json
Load /usr/share/xapi/vm-templates/windows-server-2012-r2-64bit.json
Load /usr/share/xapi/vm-templates/sles-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/windows-server-2016-64bit.json
Load /usr/share/xapi/vm-templates/oel-8.json
Load /usr/share/xapi/vm-templates/base-sle-hvm-64bit.json
Load /usr/share/xapi/vm-templates/base-kylin-7.json
Load /usr/share/xapi/vm-templates/kylin-7.json
Load /usr/share/xapi/vm-templates/debian-8.json
Load /usr/share/xapi/vm-templates/windows-server-2019-64bit.json
Load /usr/share/xapi/vm-templates/sled-12-sp3-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-uefi.json
Load /usr/share/xapi/vm-templates/sles-12-sp4-64bit.json
Load /usr/share/xapi/vm-templates/sl-7.json
Load /usr/share/xapi/vm-templates/ubuntu-20.04.json
Load /usr/share/xapi/vm-templates/windows-10-32bit.json
Load /usr/share/xapi/vm-templates/ubuntu-16.04.json
Load /usr/share/xapi/vm-templates/other-install-media.json
Load /usr/share/xapi/vm-templates/windows-8-32bit.json
Load /usr/share/xapi/vm-templates/base-hvmlinux.json
Load /usr/share/xapi/vm-templates/base-el-7.json
Load /usr/share/xapi/vm-templates/centos-8.json
Load /usr/share/xapi/vm-templates/sles-12-sp5-64bit.json
Load /usr/share/xapi/vm-templates/debian-10.json
Load /usr/share/xapi/vm-templates/ubuntu-18.04.json
Load /usr/share/xapi/vm-templates/base-windows-8.json
Destroy 552bce37-51b2-445d-84f2-5f33fa112d7e
Insert 552bce37-51b2-445d-84f2-5f33fa112d7e
Insert 7279a78a-4756-4fc3-99f0-3e7694c0319e
Insert 381ebb02-96d5-11e7-92b9-b8ca3a97c5fc
Insert 17a818b5-20a6-4d34-a7ef-320da9ef4c14
Insert e9763585-f70a-4526-bfcb-822064742e9f
Insert 7774689b-4ca1-4dea-8545-dddd6b64c17f
Insert f873abe0-b138-4995-8f6f-498b423d234d
Insert dda40663-76e5-45dd-a644-7eb0bed6a1f7
Insert c060fa00-8c96-4eb8-bcc9-772daaa01885
Insert 612863ed-900d-456d-b4b7-38b70915fd1f
Insert 847f7f36-6da8-487d-940d-f0f06939a1b6
Insert d986ea98-09fa-4e9a-9ee6-e6c78119496f
Insert 03d30863-86a2-428e-94c8-88ddfcb8cd29
Insert c15fab79-6cce-4e1f-916f-a64b98ff9e7d
Insert 9caee571-3b07-4673-940d-1d687b2818d6
Insert 110ecfa7-0fe4-4b35-a247-0b0141a738ba

[17:03 localhost ~]# xe template-list  | grep name-label
          name-label ( RW): Windows Server 2012 (64-bit)
          name-label ( RW): CoreOS
          name-label ( RW): Windows Server 2012 R2 (64-bit)
          name-label ( RW): SUSE Linux Enterprise Server 12 SP4 (64-bit)
          name-label ( RW): Windows Server 2019 (64-bit)
          name-label ( RW): Oracle Linux 8
          name-label ( RW): SUSE Linux Enterprise Server 12 SP5 (64-bit)
          name-label ( RW): Windows 8.1 (64-bit)
          name-label ( RW): Red Hat Enterprise Linux 7
          name-label ( RW): Other install media
          name-label ( RW): SUSE Linux Enterprise 15 (64-bit)
          name-label ( RW): SUSE Linux Enterprise Desktop 12 SP4 (64-bit)
          name-label ( RW): Debian Buster 10
          name-label ( RW): Windows 10 (32-bit)
          name-label ( RW): Red Hat Enterprise Linux 8
          name-label ( RW): Windows 10 (64-bit)
          name-label ( RW): Ubuntu Bionic Beaver 18.04
          name-label ( RW): Scientific Linux 7
          name-label ( RW): Ubuntu Xenial Xerus 16.04
          name-label ( RW): Oracle Linux 7
          name-label ( RW): NeoKylin Linux Server 7
          name-label ( RW): Windows Server 2016 (64-bit)
          name-label ( RW): Debian Jessie 8.0
          name-label ( RW): SUSE Linux Enterprise Desktop 12 SP3 (64-bit)
          name-label ( RW): CentOS 7
          name-label ( RW): SUSE Linux Enterprise Server 12 SP3 (64-bit)
          name-label ( RW): CentOS 8
          name-label ( RW): Debian Stretch 9.0
          name-label ( RW): Ubuntu Focal Fossa 20.04
          name-label ( RW): Windows 8.1 (32-bit)
[17:03 localhost ~]# uname -a
Linux localhost 4.19.0+1 #1 SMP Tue Oct 27 20:14:25 CET 2020 x86_64 x86_64 x86_64 GNU/Linux

```

I'll keep the ticket open for a while, I need to quick check if cloudstack basic VM lifecycle passes and then will close it.

**Comment by rhtyd** [comment]
Packages that got upgraded for reference:
```
Updating:
 ca-certificates                             noarch                             2020.2.41-70.0.el7_8                                   xcp-ng-updates                             382 k
 kernel                                      x86_64                             4.19.19-7.0.9.1.xcpng8.2                               xcp-ng-updates                              30 M
 sudo                                        x86_64                             1.8.23-10.el7_9.1                                      xcp-ng-updates                             842 k
 uefistored                                  x86_64                             0.2.6-2.xcpng8.2                                       xcp-ng-updates                              41 k
 xcp-ng-deps                                 noarch                             8.2.0-10                                               xcp-ng-updates                             9.5 k
 xen-dom0-libs                               x86_64                             4.13.1-9.8.3.xcpng8.2                                  xcp-ng-updates                             621 k
 xen-dom0-tools                              x86_64                             4.13.1-9.8.3.xcpng8.2                                  xcp-ng-updates                             2.4 M
 xen-hypervisor                              x86_64                             4.13.1-9.8.3.xcpng8.2                                  xcp-ng-updates                             2.3 M
 xen-libs                                    x86_64                             4.13.1-9.8.3.xcpng8.2                                  xcp-ng-updates                              36 k
 xen-tools                                   x86_64                             4.13.1-9.8.3.xcpng8.2                                  xcp-ng-updates                              29 k
 xenopsd                                     x86_64                             0.150.2-1.1.xcpng8.2                                   xcp-ng-updates                              74 k
 xenopsd-cli                                 x86_64                             0.150.2-1.1.xcpng8.2                                   xcp-ng-updates                             1.3 M
 xenopsd-xc                                  x86_64                             0.150.2-1.1.xcpng8.2                                   xcp-ng-updates                             3.9 M
Installing for dependencies:
 varstored-tools                             x86_64                             0.9.1-1.xcpng8.2                                       xcp-ng-updates                              50 k


```

**Comment by olivierlambert** [comment]
If you want to have CI on a fresh XCP-ng, you can use PXE to install it with an answer file.

**Comment by rhtyd** [comment]
@olivierlambert will using the netboot ISO install latest packages  https://xcp-ng.org/#easy-to-install ?

**Comment by olivierlambert** [comment]
It should but I don't want tell you something wrong. Ping @stormi

**Comment by rhtyd** [comment]
Looks like it should based on pkg repo from https://updates.xcp-ng.org/netinstall/8.2/Packages/

**Comment by rhtyd** [comment]
I rebuild the test env, now it seems to be working OK for basic VM lifecycle tests (https://download.cloudstack.org/templates/mbx/xcpng82.qcow2). I'll close the issue now, with a remark that users may want to have a new 8.2 ISO with the latest kernel and pkg updates.

Thanks for jumping on this quickly @olivierlambert - cheers and happy weekends.

**Comment by olivierlambert** [comment]
You are welcome. We are committed to assist your effort of Cloudstack+XCP-ng. Feel free to create an issue anytime you need help!

**Comment by stormi** [comment]
> @olivierlambert will using the netboot ISO install latest packages https://xcp-ng.org/#easy-to-install ?

Not at the moment, because the netinstall repo contains the same packages as the installer ISO contains, without using the updates repository.

**Comment by stormi** [comment]
> I rebuild the test env, now it seems to be working OK for basic VM lifecycle tests (https://download.cloudstack.org/templates/mbx/xcpng82.qcow2). I'll close the issue now, with a remark that users may want to have a new 8.2 ISO with the latest kernel and pkg updates.

We'll probably release such ISOs from time to time, given how long the 8.2 release will be supported.
