### ISSUE TITLE
export vm to xva failure

### ISSUE THREAD

**Issue by AlexProfi** [xcp-ng/xcp#485]
Hello
I use xcp-ng 8.0
I try to export vm that storaged on iscsi

and in logs (help show xcp-ng logs) I get following
```

2021-03-24 19:11:03,320 WARN  XenAdmin.Network.TaskPoller [193] - Action failed due to API failure:
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at XenAdmin.Network.TaskPoller.poll()
   at XenAdmin.Network.TaskPoller.PollToCompletion()
   at XenAdmin.Actions.VMSnapshotCreateAction.Run()
   at XenAdmin.Actions.AsyncAction.RunWorkerThread(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2021-03-24 19:11:03,367 INFO  XenAPI.Session [193] - Invoking JSON-RPC method 'task.destroy'
2021-03-24 19:11:03,414 ERROR XenAdmin.Actions.AsyncAction [193] - The specified storage repository has insufficient space
2021-03-24 19:11:03,414 WARN  Audit [193] - Operation failure: VMSnapshotCreateAction: Kaluga: VM a3334e02-d6a2-a865-58be-0a3fdb8d4383 (osm-linux-iscsi): Pool d0c94466-ee05-8861-5000-12f42c136099 (Kaluga): Creating a snapshot...
2021-03-24 19:12:13,021 INFO  Audit [Main program thread] - Operation started: ExportVmAction: Kaluga: VM a3334e02-d6a2-a865-58be-0a3fdb8d4383 (osm-linux-iscsi): Pool d0c94466-ee05-8861-5000-12f42c136099 (Kaluga): Preparing to export
2021-03-24 19:12:13,084 INFO  XenAPI.Session [205] - Invoking JSON-RPC method 'task.create'
2021-03-24 19:12:13,131 INFO  XenAPI.Session [205] - Invoking JSON-RPC method 'task.remove_from_other_config'
2021-03-24 19:12:13,177 INFO  XenAPI.Session [205] - Invoking JSON-RPC method 'task.add_to_other_config'
2021-03-24 19:12:13,224 INFO  XenAPI.Session [205] - Invoking JSON-RPC method 'task.remove_from_other_config'
2021-03-24 19:12:13,271 INFO  XenAPI.Session [205] - Invoking JSON-RPC method 'task.add_to_other_config'
2021-03-24 19:12:26,640 WARN  XenAdmin.Network.TaskPoller [Progress polling thread for ExportVmAction for osm-linux-iscsi] - Action failed due to API failure:
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at XenAdmin.Network.TaskPoller.poll()
   at XenAdmin.Network.TaskPoller.PollToCompletion()
   at XenAdmin.Actions.ExportVmAction.progressPoll()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2021-03-24 19:12:26,640 INFO  XenAPI.Session [Progress polling thread for ExportVmAction for osm-linux-iscsi] - Invoking JSON-RPC method 'task.destroy'
2021-03-24 19:12:26,687 WARN  XenAdmin.Actions.ExportVmAction [205] - Export of VM osm-linux-iscsi failed
System.IO.EndOfStreamException: End of stream reached with 17 bytes left to read
   at IO.unmarshal_n_into(Stream stream, UInt32 n, Byte[] buffer)
   at Export.nextData(Stream input, Stream output, verifyCallback callback, UInt32 size)
   at Export.nextHeader(Stream input, Stream output, verifyCallback callback)
   at Export.verify(Stream input, Stream output, cancellingCallback cancelling, verifyCallback callback)
   at XenAdmin.Actions.ExportVmAction.HttpGet(String filename, Uri uri)
   at XenAdmin.Actions.ExportVmAction.Run()
2021-03-24 19:12:26,703 ERROR XenAdmin.Actions.AsyncAction [205] - System.Exception: Export failed
   at XenAdmin.Actions.ExportVmAction.Run()
   at XenAdmin.Actions.AsyncAction.RunWorkerThread(Object o)
2021-03-24 19:12:26,703 WARN  Audit [205] - Operation failure: ExportVmAction: Kaluga: VM a3334e02-d6a2-a865-58be-0a3fdb8d4383 (osm-linux-iscsi): Pool d0c94466-ee05-8861-5000-12f42c136099 (Kaluga): Export failed
2021-03-24 19:13:05,734 INFO  XenAdmin.ConsoleView.VNCGraphicsClient [Main program thread] - VNCGraphicsClient.SetSendScanCodes newSendScanCodes=False

```

how to resolve it?

**Comment by olivierlambert** [comment]
Hi!

This repo is more made to report confirmed/reproducible issues on supported XCP-ng versions. You should ask on our community forum for assistance: https://xcp-ng.org/forum

Note that:
* XCP-ng 8.0 isn't supported anymore
* XCP-ng Center is not an officially supported client
* The error is not an XCP-ng bug, but a configuration problem, see `The specified storage repository has insufficient space`.

See you on the forum :+1:

**Comment by nagilum99** [comment]
Also reading the logs (as you already have and posted them) could help:
"2021-03-24 19:11:03,414 ERROR XenAdmin.Actions.AsyncAction [193] - The specified storage repository has insufficient space"

**Comment by olivierlambert** [comment]
That's what I said already @nagilum99 :wink: (point 3)

**Comment by nagilum99** [comment]
Nevermind, didn't see that. ;)

**Comment by AlexProfi** [comment]
Thanks for reply. is it problem with storage iscsi where the vm is stored or with target disk where I try to export vm?

**Comment by AlexProfi** [comment]
I understand. it is problem with create snapshot firstly. I can't do it because low disk space. So I try to export but export firstly make snapshot.

**Comment by olivierlambert** [comment]
As requested initially, please create a thread [on the forum](https://xcp-ng.org/forum), it will be more appropriate to continue the discussion.
